#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4.2
    with:
      duckdb_version: v1.4.2
      ci_tools_version: v1.4.2
      extension_name: ducklake
      exclude_archs: "linux_arm64;linux_amd64_musl;osx_amd64;windows_amd64;windows_arm64;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads"

  duckdb-next-deploy:
    name: Deploy extension binaries
    needs: duckdb-next-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.4.2
    secrets: inherit
    with:
      extension_name: ducklake
      duckdb_version: v1.4.2
      ci_tools_version: v1.4.2
      exclude_archs: "linux_arm64;linux_amd64_musl;osx_amd64;windows_amd64;windows_arm64;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads"
      deploy_latest: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}
      deploy_versioned: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}
